version: "3"

services:
  test-cont:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: test-app
    volumes:
      - .:/test-app
    ports:
      - "8000:8000"